let data = {"javascript":[`what is repl?~Read Evaluate Print Loop`,
`Why would you use a do/while loop~ When you need the loop to run at least once`,
`how do you typecast (coerce) a string named 'string' to an int?~parseInt(string)`,
`how do you combine strings?~use the +`,
`how do you get an index in the forEach loop?~array.forEach((element, index) => { your function here })`,
"what is the format for string interpolation?~backticks, and ${}",
`how can you search within a string and get a boolean?~string.search('search string')`,
`how can you search within a string and get the index?~string.indexOf('search string')`,
`how do you print to the screen?~console.log() (for most things) or console.dir() (for objects that you want to explore in the console.)`,
`how would you create a new object of the class Dog named spot?~spot = new Dog(args)`,
`how can you make a blank array called myArr?~myArr = []`,
`how can you remove trailing whitespace and newlines?~inputString = String.trim(inputString)`,
`generate a random number between 0 and 4.~Math.random(0)*4`,
`what are the falsey values in javascript?~false, 0 (zero), '' or "" (empty string), null, undefined, NaN`,
`how do you evaluate for truth?~Boolean(thingToBeTested) \n OR !!thingToBeTested`,
`how do you increment a variable?~counter++ or counter += 1`,
`what is the easiest way to loop 10x?~use a for loop`,
`how do you write 3 to the 5th?~Math.pow(3,5)`,
`what does regex.match(string) return in either case?~if true it returns an object (which evaluates to true), if false it returns false.`,
`what does unshift do?~it adds to the beginning of an array.`,
`how do you add a new array element to the beginning of an array?~unshift`,
`how do you add a new array element to the end of an array?~push`,
`how do you add a new array element to a specific index of an array?~array.splice(index,numElementsToDelete,itemToInsert)`,
`check if an array has an element equal to x. (you are looking for a boolean)~array.includes(element)`,
`check if an array has an element equal to x. (you are looking for the index)~array.indexOf(element)`,
`delete an element of an array~array.splice(index,numElementsToDelete)`,
`iterate over every element in an array.~array.forEach() (this is not recommended because it is inescapable)`,
`how can you filter an array with a function?~array.select{|element| element.even?} will return even elements.`,
`how can you filter an array with a function BUT return the array elements that failed the function?~array.reject{|element| element.even?} will return odd elements.`,
`explain how the .sort method works~numbers.sort((a, b) => a - b) will numerically sort lowest to highest a-z`,
`delete the element at index 2 of the array 'noses'~noses.delete(2,1)`,
`what is the syntax for array.find()?~array.find((element) => {return element > 0})`,
`what is the difference in array.find and array.filter?~find returns one element, filter returns all matches.`,
`what is the format for array.reduce?~array.reduce((accumulator,element) => accumulator + element)`,
`what is the format for array.sort?~array.sort(elementA, elementB => elementA - elementB)`,
`how does array.sort work?~the formula in it returns a number. if it is positive, one side goes first. negative and the other side goes first. 0? that's anyone's guess.`,

],

"ruby":[`what is repl?~Read Evaluate Print Loop`,
`what is irb?~interactive ruby`,
`what is pry~a ruby debugging tool`,
`how do you use pry? (2 lines)~require 'pry' ; binding.pry`,
`how do you typecast (coerce) a string named 'string' to an int?~string = string.to_i`,
`how do you combine strings?~use the +`,
'what is the format for string interpolation?~double quotes, and #{}',
`how can you search within a string and get a boolean?~string.include?('search string')`,
`how can you search within a string and get the index?~string.index('search string')`,
`how do you print to the screen?~puts or print, depending if you want a line ending or not`,
`how would you create a new object of the class Dog named spot?~spot = Dog.new`,
`how can you make an array called myArr? (2 ways)~myArr = [] ; myArr = Array.new`,
`what is the best way to show an array in output?~p(arrayName), puts doesn't output anything.`,
`how can you remove trailing whitespace and newlines?~.strip`,
`generate a random number between 0 and 4.~rand(0..4)`,
`what is the best way to check the variable counter for nil?~counter.nil?`,
`what is indicated by a method that ends in ?~it returns a boolean usually`,
`what are the falsey values in ruby?~false and nil`,
`how do you evaluate for truth?~put an !! in front of it. `,
`explain short circuit evaluation~put the more restrictive truth tests first in a multi && check so that they fail first and not all tests need to be evaluated.`,
`show a basic rspec test.~
require 'rspec/autorun'
describe 'the name of the function to be tested' do
    it 'should do a specific thing' do
    expect(functionName(args)).to eq(expectedOutput)
  end
end
`,
`how do you increment a variable?~counter += 1`,
`what is the easiest way to loop 10x?~10.times {}`,
`how do you write 3 to the 5th?~3**5`,
`what does regex.match(string) return in either case?~if true it returns an object (which evaluates to true), if false it returns false.`,
`what is the shovel operator?~<< it is the same as .push`,
`what does << do?~it is the same as push. it adds to the end of an array.`,
`what does unshift do?~it adds to the beginning of an array.`,
`how do you add a new array element to the beginning of an array?~unshift`,
`how do you add a new array element to the end of an array?~push or shovel operator <<`,
`how do you add a new array element to a specific index of an array?~array.insert(index,element to insert)`,
`check if an array has an element equal to x. (you are looking for a boolean)~array.include(element)`,
`check if an array has an element equal to x. (you are looking for the index)~array.index(element)`,
`delete an element of an array~array.delete(element)`,
`iterate over every element in an array.~array.each{|each|}`,
`iterate over every element in an array AND keep the index.~array.each_with_index{|each,index|}`,
`how is .map unlike .each?~.map returns a new array with the values returned from each loop of the function. each does not.`,
`how can you mutate the array with map?~array.map! will mutate the input array`,
`how can you filter an array with a function?~array.select{|element| element.even?} will return even elements.`,
`how can you filter an array with a function BUT return the array elements that failed the function?~array.reject{|element| element.even?} will return odd elements.`,
`explain how the .sort method works~array.sort(|first_element, second_element| second_element <=> first_element) will return a reverse order sort. the <=> (spaceship operator) returns -1,0,or 1.`,
`delete the element at index 2 of the array 'noses'~noses.delete_at(2)`,
`how do you make a string all lowercase?~string = string.downcase`,
`How can you randomly select an element from an array named "dogs"?~dogs.sample`,
`How do you do string substitution?~stringName.gsub('-',' ')`,
`How can you get the length of an array?~array.length or array.size`,
`How can you create a new hash named 'myHash'? (2 ways)~ myhash = {} or myHash = Hash.new`,
`What is this (:dogs) called?~A symbol.`,
`How do you iterate over a hash?~ .each, .each_key, and .each_value are some methods. You can also manually iterate over hashName.keys or hashName.values.`,
`How can you see if a value is in a hash?~hashName.has_value(value) (or .value(value)) will return a bool.`,
`How can you see if a key is in a hash?~hashName[:symbol] or hashName['string'] depending on the key format. This will return nil if it isn't found and will then need to be dealt with. hashName.fetch(:symbol) will return an error. hashName.key? (or .has_key?) will return a boolean.`,
`How do you reverse a string or array?~string.reverse will return it reversed but not mutate. string.reverse! will mutate.`
]
}

// console.log(data)
module.exports = data
